-- Run this in Supabase SQL Editor.

create table if not exists public.entries (
  id bigint generated by default as identity primary key,
  profile_id text not null,
  profile_name text not null,
  day_index integer not null check (day_index between 0 and 6),
  media_type text not null check (media_type in ('photo','video')),
  media_url text not null,
  theme text not null,
  created_at timestamptz not null default now()
);

alter table public.entries enable row level security;

create policy "Public can read adventure entries"
on public.entries for select
to anon
using (true);

create policy "Public can add adventure entries"
on public.entries for insert
to anon
with check (true);

-- Create a PUBLIC storage bucket named: adventure-media
-- Then add these storage policies:

create policy "Public can upload adventure media"
on storage.objects for insert
to anon
with check (bucket_id = 'adventure-media');

create policy "Public can view adventure media"
on storage.objects for select
to anon
using (bucket_id = 'adventure-media');
