-- Run once in Supabase SQL Editor after the earlier setup.

create table if not exists public.daily_missions (
  holiday_id text not null,
  day_index integer not null check (day_index between 0 and 30),
  theme text not null,
  photo_instruction text not null,
  video_question text not null,
  updated_at timestamptz not null default now(),
  primary key (holiday_id, day_index)
);

create table if not exists public.secret_assignments (
  holiday_id text not null,
  explorer_profile_id text not null,
  subject_profile_id text not null,
  updated_at timestamptz not null default now(),
  primary key (holiday_id, explorer_profile_id)
);

create table if not exists public.secret_photos (
  id bigint generated by default as identity primary key,
  holiday_id text not null,
  explorer_profile_id text not null,
  subject_profile_id text not null,
  partner_profile_id text not null,
  media_url text not null,
  storage_path text not null,
  created_at timestamptz not null default now(),
  unique (holiday_id, explorer_profile_id, partner_profile_id)
);

alter table public.daily_missions enable row level security;
alter table public.secret_assignments enable row level security;
alter table public.secret_photos enable row level security;

create policy "Public can read daily missions"
on public.daily_missions for select to anon using (true);

create policy "Public can add daily missions"
on public.daily_missions for insert to anon with check (true);

create policy "Public can update daily missions"
on public.daily_missions for update to anon using (true) with check (true);

create policy "Public can read secret assignments"
on public.secret_assignments for select to anon using (true);

create policy "Public can add secret assignments"
on public.secret_assignments for insert to anon with check (true);

create policy "Public can update secret assignments"
on public.secret_assignments for update to anon using (true) with check (true);

create policy "Public can read secret photos"
on public.secret_photos for select to anon using (true);

create policy "Public can add secret photos"
on public.secret_photos for insert to anon with check (true);

create policy "Public can update secret photos"
on public.secret_photos for update to anon using (true) with check (true);
